name: PaperSpigot CI

on:
  push:
    branches: [ master, ver/1.8.8 ]
  pull_request:
    branches: [ master, ver/1.8.8 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: "Setup Gradle cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Git
        run: |
          git config --global user.email "paperspigot@example.com"
          git config --global user.name "PaperSpigot CI/CD"
          git config --global init.defaultBranch ver/1.8.8
      - name: Grant execute permissions
        run: |
          chmod -R +x ./scripts/
          chmod +x gradlew
          chmod +x nozzle
      - name: Setup Nozzle environment
        run: ./nozzle setup
      - name: Build Nozzle JAR
        run: ./gradlew build